In [14]:
import pandas as pd
#chargement des données
dataset = pd.read_csv('hospital_patients.csv')
#pour afficher le tableau  dataset.head()
dataset.head()

   Âge   Sexe  Taille (cm)  Poids (kg) Diagnostic  Statut
0   45  Homme          175          78         A1       1
1   60  Femme          162          70         B2       0
2   30  Homme          180          85         A1       1
3   50  Femme          158          65         C3       0
4   70  Homme          170          80         B2       1

In [20]:
#pretraitement des données 
#gestion des valeurs manquantes
dataset['Âge'].fillna(dataset['Âge'].mean(),inplace=True)#la moyenne des Ages
dataset['Taille (cm)'].fillna(dataset['Taille (cm)'].mean(),inplace=True) #la myenne des Tailles
dataset['Poids (kg)'].fillna(dataset['Poids (kg)'].mean(),inplace=True)#la moyenne des poids
dataset['Sexe'].fillna(dataset['Sexe'].mode()[0],inplace=True)#valeurs la plus courante
dataset['Diagnostic'].fillna(dataset['Diagnostic'].mode()[0],inplace=True) #valeurs la plus courante

In [27]:
#Encodage des valeurs catégorielles
dataset_encoded = pd.get_dummies(dataset,columns = ['Sexe','Diagnostic'],drop_first=True)
dataset_encoded.head(10)

,Âge,Taille (cm),Poids (kg),Statut,Sexe_Homme,Diagnostic_B2,Diagnostic_C3
0,45,175,78,1,True,False,False
1,60,162,70,0,False,True,False
2,30,180,85,1,True,False,False
3,50,158,65,0,False,False,True
4,70,170,80,1,True,True,False
5,55,165,68,1,False,False,False
6,40,172,75,0,True,False,True
7,65,160,72,1,False,True,False
8,35,178,82,1,True,False,False
9,48,167,69,0,False,False,True

In [32]:
#Normalisation des colonnes numériques
# importation bib standardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
dataset_encoded[['Âge','Taille (cm)','Poids (kg)']]=scaler.fit_transform(dataset_encoded[['Âge','Taille (cm)','Poids (kg)']])
dataset_encoded.head(10)

,Âge,Taille (cm),Poids (kg),Statut,Sexe_Homme,Diagnostic_B2,Diagnostic_C3
0,-0.391449,0.875253,0.570352,1,True,False,False
1,0.831829,-0.930825,-0.697097,0,False,True,False
2,-1.614727,1.569899,1.679369,1,True,False,False
3,0.016310,-1.486541,-1.489252,0,False,False,True
4,1.647347,0.180608,0.887214,1,True,True,False
5,0.424070,-0.514038,-1.013959,1,False,False,False
6,-0.799208,0.458466,0.095059,0,True,False,True
7,1.239588,-1.208683,-0.380235,1,False,True,False
8,-1.206967,1.292041,1.204076,1,True,False,False
9,-0.146793,-0.236179,-0.855528,0,False,False,True

In [33]:
#Etape:2 Séparation des données 
from sklearn.model_selection import train_test_split
X= dataset_encoded.drop('Statut',axis=1)
y = dataset_encoded['Statut']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:
#Modélisation
#Entrainement du modèle du modèle de regression losistique
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [42]:
#Etaoe4:prediction et evaluation
y_pred= model.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix
acc= accuracy_score(y_test,y_pred)
conf_matrix=confusion_matrix(y_test,y_pred)
print("Exacritude:",acc)
print("Matrice de confusion\n:",conf_matrix)

Exacritude: 0.5
Matrice de confusion
: [[0 1]
 [0 1]]